Implemented inputs validation, path recstriction and child components…
adragicevicc/nqode-intentship pull request #11
Opened 2022-11-24 12:30 UTC by adragicevicc

… rerender

2022-11-24 13:25 UTC, milos-majkic requested changes

2022-11-24 13:25 UTC, milos-majkic commented on .env
> +REACT_APP_BASE_URL=https://library-back-internship.herokuapp.com
Add new line at end of file

2022-11-24 13:25 UTC, milos-majkic commented on src/components/SideBar/Sidebar.tsx
> +            key={name}
Why do you use the name as a key, if we have the same names it produces conflicts in the DOM tree.
Replace name value with index from map function. This is not the best solution but in our case, it is good. In general, we need to provide a unique and stable keys for the list's elements.

2022-11-25 12:56 UTC, vkotarlic approved these changes

2022-11-25 12:58 UTC, merged