Implemented admin functionalities with put and delete requests on books
adragicevicc/nqode-intentship pull request #4
Opened 2022-11-14 15:59 UTC by adragicevicc

2022-11-14 16:24 UTC, petarnqode requested changes

2022-11-14 16:24 UTC, petarnqode commented on src/components/core/Input/Input.tsx
> +      <input className={classes['c-input']} name={name} onChange={onChange} value={value}></input>
We should user /> on end when component don't have children

2022-11-15 08:17 UTC, petarnqode requested changes

2022-11-15 08:17 UTC, petarnqode commented on src/components/BookDialog/BookDialog.tsx
> +        </div>
Can we refactor this code a bit, make one common component?

2022-11-15 08:23 UTC, vkotarlic requested changes

2022-11-15 08:23 UTC, vkotarlic commented on src/components/BooksList/BooksList.tsx
> +};
Here we should use Interface as we agreed on start

2022-11-15 08:23 UTC, vkotarlic commented on src/pages/Admin/Dashboard/Dashboard.tsx
> +      <BooksList filter="rented-current" />
I wouldn't pass filter as prop here if that is possible

2022-11-15 08:23 UTC, vkotarlic commented on src/components/BooksList/BooksList.tsx
> +  filter?: string;
Here we should type this as `'rented' | 'all'`

2022-11-15 10:00 UTC, merged