Implemented admin side bar menu, visible through Dashboard layout
adragicevicc/nqode-intentship pull request #8
Opened 2022-11-21 15:44 UTC by adragicevicc

2022-11-22 08:06 UTC, petarnqode requested changes

2022-11-22 08:06 UTC, petarnqode commented on src/components/BookListItem/BookListItem.tsx
> +  const path = role === 'ADMINISTRATOR' ? `/dashboard/book/${id}` : `/book/${id}`;
Can we have users role types somewhere in consts so we don't type it every time its error prone?

2022-11-22 08:06 UTC, petarnqode commented on src/pages/Login/Login.tsx
> +      navigate('/');
Can we have users role types somewhere in consts so we don't type it every time its error prone?

2022-11-22 08:06 UTC, petarnqode commented on src/components/SideBar/Sidebar.tsx
> +        {sideBarLinks.map((el) => (
Can we use destruct here, { link, name } ?

2022-11-22 10:42 UTC, vkotarlic requested changes

2022-11-22 10:42 UTC, vkotarlic commented on src/components/BookListItem/BookListItem.tsx
> +  const path = role === roleTypes.adminRole ? `/dashboard/book/${id}` : `/book/${id}`;
Can you use `isAdminRole()` method here?

2022-11-22 10:42 UTC, vkotarlic commented on src/components/SideBar/SideBar.module.scss
> +.c-side-bar {
My suggestion is to name this `.c-sidebar` no need for `-` but it is just suggestion

2022-11-22 10:42 UTC, vkotarlic commented on src/components/SideBar/SideBar.module.scss
> +  }
Since here i see active my guess this should be modifier of `__options-item` so `--active`

2022-11-22 10:42 UTC, vkotarlic commented on src/components/SideBar/Sidebar.tsx
> +              classes[`${pathname === link ? 'c-side-bar__options-item-active' : ''}`]
Please check out comment in scss file about `--active`

2022-11-22 10:42 UTC, vkotarlic commented on src/pages/Login/Login.tsx
> +    if (role === roleTypes.userRole) {
Same as upper comment here you could use `isRoleAdim()` method

2022-11-23 08:13 UTC, merged

2022-11-23 08:27 UTC, milos-majkic requested changes

2022-11-23 08:27 UTC, milos-majkic commented on src/components/Navbar/Navbar.tsx
> +        <Link to={`/`} className={classes['c-navbar__link']}>
There is no need to use curly brackets when you pass a string to an attribute to, replace this with `to="/"`